name: Backend Tests

on:
  push:
    branches:
      - develop
      - backend
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore ExamSystem.Backend/ExamSystem.Tests/ExamSystem.Tests.csproj

      - name: Build
        run: dotnet build ExamSystem.Backend/ExamSystem.Tests/ExamSystem.Tests.csproj --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test ExamSystem.Backend/ExamSystem.Tests/ExamSystem.Tests.csproj --no-build --configuration Release --verbosity normal