name: Frontend CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ExamSystem.Frontend/package-lock.json

      - name: Install Dependencies
        working-directory: ExamSystem.Frontend
        run: npm install

      - name: Build Project
        working-directory: ExamSystem.Frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ExamSystem.Frontend/dist
